### ISSUE TITLE
Frame issue

### ISSUE THREAD

**Issue by YorhaX2P** [Zerui18/Frame#1]
Hello,

I have added a Lock screen and a Home screen for the wallpaper.

Down of scroll (Respring) click the button was not working.. I've decided to respring using CCPower.. Just respring it and the Lock & Home screen doesn't show up for the animated wallpaper, what wrong with that?

I've installed it here,
Frame (arm64e-iOS14) 2.4.2 from REPO https://zerui18.github.io/zx02/
Xeninfo 2.2.9 from REPO https://junsiphone.com/supersecret/
Xen HTML 2.0~beta9 from REPO https://xenpublic.incendo.ws/

I have created the folder from Documents > com.ZX02.Frame has been downloaded off the two videos. and Read, Write, Execute have been enabled...

I'm currently using iPhone 7 Plus - 128GB (A1784) Red product
iOS version - 14.3
Jailbroken Taurine version - 1.0.4
Sileo version - 2.1

**Comment by Zerui18** [comment]
You've installed the wrong version of Frame. Install the one named "Frame" without the iOS 14.

**Comment by YorhaX2P** [comment]
> You've installed the wrong version of Frame. Install the one named "Frame" without the iOS 14.

I've installed this without the iOS 14, when you click any apps that were trying to open and stopped working, I was trying to spam click any app 5x times would let me open the app. So the animated wallpaper was still working well.

**Comment by YorhaX2P** [comment]
> You've installed the wrong version of Frame. Install the one named "Frame" without the iOS 14.

Are you working on an issue to resolve? It's been for two days, I'd love to hear you for the update.

**Comment by Zerui18** [comment]
Hi, the issue of apps not opening on tap is a known bug that may rarely occur. It's usually fixed with a respring or reboot. In fact, it has not occured on my own devices for months so I'm unable to debug it.

**Comment by YorhaX2P** [comment]
> 

Hello,

Are you able to update that issue that has been fixed? Because you have released of Frame 3 new version. Also are you going to drop the support of Frame 2 version and only focus on Frame 3?

But I like frame 3, it is pretty nice and features more as well.

**Comment by Zerui18** [comment]
Hi, may I know what is the issue that you are experiencing?

I will likely stop updating Frame 2 from this point onwards and focus on improving Frame 3.

**Comment by YorhaX2P** [comment]
> Hi, may I know what is the issue that you are experiencing?
> 
> I will likely stop updating Frame 2 from this point onwards and focus on improving Frame 3.

I've tested from Frame 3 and it's the same issue from Frame 2 happens too...
