### ISSUE TITLE
Less of an issue, more of a request

### ISSUE THREAD

**Issue by jecoteco** [Zerui18/Frame#10]
I've used Frame for a long time and it is one of my favourite tweaks. I can't impose but is frame something that is possible on IOS 15 rootless?
I'm now using Dopamine (Fugu15 Max beta 8).

**Comment by Zerui18** [comment]
Hi, i really appreciate you and everyone's support for Frame. Technically it is possible on iOS 15 too. However, I will not be updating it primarily because I do not have a jailbroken iOS 15 device to test it - remote testing would be undesirable as it's less reliable and much more time consuming.

**Comment by jecoteco** [comment]
Would corellium be an option for testing?

**Comment by Zerui18** [comment]
I don't have any experience using Corellium. It surely looks promising as a testing platform for jailbroken tweaks, but I can't say how easy it is to setup the testing environment properly.

**Comment by jecoteco** [comment]
It's not too difficult to setup. Contrary to a physical phone you can chose the iOS version that you want. Which is exactly what we want. Side loading ipas works the the same way as a normal phone. Once jailbroken via TrollStore and Dopamine you can test out tweaks in an emulated environment. The only issue is the license. It used to be free but now there is a monthly subscription.

![image](https://user-images.githubusercontent.com/55798271/233757112-ddfa99cb-f931-4c56-be4f-857679a16d91.png)

**Comment by Zerui18** [comment]
I see, thanks for the insights! Indeed it seems like a powerful platform and a pity it costs quite a hefty sum to use.
