### ISSUE TITLE
Can‘t instal or uninstall new vision

### ISSUE THREAD

**Issue by ZeroX1ng** [Zerui18/Frame#11]
I saw a new vision this morning,so I uninstall 3.0.0-4 ,but when i instal new vision (rootfull ios14)I meet this error:![image](https://github.com/Zerui18/Frame/assets/34992990/a4013c40-e8b2-4523-9050-38439f419709)
How could I fix it？ I can't install or uninstall it

iOS 14.2 taurine1.1.8

**Comment by Zerui18** [comment]
你可以试着更新一下你的package manager和dpkg。

**Comment by ZeroX1ng** [comment]
问题大概解决了…我删除了var/lib/dpkg/status里的对应字段。
然后解包查看了一下，您标注的Rootful实际解包出来frame app对应路径是位于var/jb，该路径看起来似乎是rootlees使用的(或者这是打包错误？)，而动态库位置是rootful对应的/Library/MobileSubstrate/DynamicLibraries，估计这就是错误产生的原因吧。

(我的sileo及对应依赖均为当前最新版本)

**Comment by Zerui18** [comment]
哦了解了，应该是我打包时FrameApp的路径错了。谢谢您提供的信息

**Comment by Zerui18** [comment]
我刚更新了一下repo上的deb文件，当中除了FrameApp还有其他一些路径错误，可以请你测试一下吗？

**Comment by ZeroX1ng** [comment]
很抱歉这么晚回复，网络访问有点不顺畅......问题解决了（除了不能覆盖安装老版本（3.0.0-4）以外

> 我刚更新了一下repo上的deb文件，当中除了FrameApp还有其他一些路径错误，可以请你测试一下吗？
> 
> 
>
