### ISSUE TITLE
frame app does not work on ipad

### ISSUE THREAD

**Issue by jank-y** [Zerui18/Frame#7]
![B9721A01-05F3-4649-8E4B-37FE32B4E17A](https://user-images.githubusercontent.com/94757612/185518781-61ee5c5c-f84e-4140-807f-ab259f00f698.jpeg)
![C750A7B8-43C8-465B-9745-A83454FE3D43](https://user-images.githubusercontent.com/94757612/185518783-5a1c51b4-8818-4ab5-8f0a-b7a32420ec89.png)
you cannot set or download wallpapers. (i have also tried putting wallpapers into the videos folder in filza.) If I could have a previous version of the tweak that is accessible through settings that would be amazing.

**Comment by ToneXum** [comment]
Same issue here. Aditionaly, the wallpaper is misaligned when imported from local
